import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Pacifico } from 'next/font/google'
import './globals.css'
import { Nav } from './components/layout/nav/nav'
import { Footer } from './components/layout/footer/footer'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-pacifico',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased flex min-h-screen flex-col`}
      >
        <Nav />
        <main className="flex-1">
          <div className="px-8 md:px-0 max-w-5xl mx-auto">{children}</div>
        </main>
        <Footer />
        <div className="absolute inset-x-0 top-0 bottom-0 z-[-1] flex flex-col">
          <div className="h-1/2 bg-zinc-100"></div>
          <div className="h-1/2 bg-white"></div>
        </div>
      </body>
    </html>
  )
}
